[pytest]
# Run tests from back_end directory only
pythonpath = back_end
testpaths = back_end/tests
asyncio_mode = auto

norecursedirs = .git __pycache__ *.egg-info venv *_venv

log_cli = true
log_level = INFO
log_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_date_format = %Y-%m-%d %H:%M:%S