#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_LICENSES.txt at the repo root.

Collects license metadata + full license text from both the Python backend
(via pip-licenses, run against back_end/nlm_backend_venv) and the JS frontend
(via npx license-checker, production deps only), then writes a single combined
file at the repo root, overwriting any existing one.

Cross-platform: Mac, Linux, Windows.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BACKEND = REPO / "back_end"
FRONTEND = REPO / "front_end"
VENV = BACKEND / "nlm_backend_venv"
FORMAT_SPEC = Path(__file__).resolve().parent / "license_checker_format.json"
OUTPUT = REPO / "THIRD_PARTY_LICENSES.txt"

SEP = "=" * 70
SUB = "-" * 70


def venv_bin(name: str) -> Path:
    # Windows venvs use Scripts/ with .exe; POSIX uses bin/.
    if os.name == "nt":
        return VENV / "Scripts" / f"{name}.exe"
    return VENV / "bin" / name


def collect_backend() -> str:
    pip_licenses = venv_bin("pip-licenses")
    if not pip_licenses.exists():
        raise SystemExit(
            f"pip-licenses not found at {pip_licenses}\n"
            f"Install it into the venv:\n"
            f"  {venv_bin('pip')} install pip-licenses"
        )
    result = subprocess.run(
        [
            str(pip_licenses),
            "--format=plain-vertical",
            "--with-license-file",
            "--no-license-path",
            "--with-urls",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def collect_frontend() -> str:
    npx = shutil.which("npx.cmd") if os.name == "nt" else shutil.which("npx")
    if not npx:
        raise SystemExit("npx not found on PATH. Install Node.js.")
    if not (FRONTEND / "node_modules").exists():
        raise SystemExit(
            f"{FRONTEND / 'node_modules'} missing. Run `npm install` in front_end/."
        )

    pkg = json.loads((FRONTEND / "package.json").read_text())
    self_id = f"{pkg['name']}@{pkg['version']}"

    result = subprocess.run(
        [
            npx,
            "license-checker",
            "--production",
            "--excludePackages",
            self_id,
            "--customPath",
            str(FORMAT_SPEC),
            "--json",
        ],
        cwd=FRONTEND,
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)

    blocks: list[str] = []
    for name, info in sorted(data.items()):
        text = (info.get("licenseText") or "").strip()
        if text == "none":
            text = ""
        blocks += [
            SEP,
            name,
            f"License: {info.get('licenses', '') or 'UNKNOWN'}",
        ]
        if info.get("repository"):
            blocks.append(f"Repository: {info['repository']}")
        if info.get("publisher"):
            blocks.append(f"Publisher: {info['publisher']}")
        blocks += [SUB, text or "(no license text bundled with package)", ""]
    return "\n".join(blocks)


def main() -> int:
    print("Collecting backend (Python) licenses...", flush=True)
    backend = collect_backend()
    print("Collecting frontend (npm, production) licenses...", flush=True)
    frontend = collect_frontend()

    header = (
        "Third-Party Software Licenses\n"
        "=============================\n"
        "This file lists the open-source dependencies bundled with this software\n"
        "and their license terms. Generated by ci/generate_third_party_licenses.py.\n"
        "Do not edit by hand; re-run the script to regenerate.\n"
    )
    body = "\n".join(
        [
            header,
            "\n\n" + "#" * 70,
            "# BACKEND  (Python, back_end/nlm_backend_venv)",
            "#" * 70 + "\n",
            backend,
            "\n" + "#" * 70,
            "# FRONTEND (npm, front_end production dependencies)",
            "#" * 70 + "\n",
            frontend,
        ]
    )
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
